<?php

namespace Bl2\Model;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * Entity object representing a skill tier which represents exactly one tier within a skill tree.
 * @ORM\Entity
 * @ORM\Table(name="skill_tier", uniqueConstraints={@ORM\UniqueConstraint(name="unique_name", columns={"skill_tree_id",
 * "order"})})
 **/
class SkillTier extends AbstractEntity {

    /**
     * @ORM\ManyToOne(targetEntity="SkillTree", inversedBy="skillTiers", fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="skill_tree_id", referencedColumnName="id", nullable=false)
     * @var Character
     **/
    protected $skillTree;

    /**
     * @ORM\Column(type="integer")
     * @var int
     **/
    protected $order;

    /**
     * @ORM\OneToOne(targetEntity="Skill")
     * @ORM\JoinColumn(name="left_skill_id", referencedColumnName="id")
     * @Serializer\SerializedName("leftSkill")
     **/
    protected $leftSkill;

    /**
     * @ORM\OneToOne(targetEntity="Skill")
     * @ORM\JoinColumn(name="middle_skill_id", referencedColumnName="id")
     * @Serializer\SerializedName("middleSkill")
     **/
    protected $middleSkill;

    /**
     * @ORM\OneToOne(targetEntity="Skill")
     * @ORM\JoinColumn(name="right_skill_id", referencedColumnName="id")
     * @Serializer\SerializedName("rightSkill")
     **/
    protected $rightSkill;

    /**
     * Creates a new skill tree by initializing is properties by using the values given in the associative array.
     *
     * @param array $data associative array holding the properties for the skill tree.
     */
    public function __construct(array $data) {
        parent::__construct($data);
    }

    /**
     * @param mixed $leftSkill
     */
    public function setLeftSkill($leftSkill) {
        $this->leftSkill = $leftSkill;
    }

    /**
     * @return mixed
     */
    public function getLeftSkill() {
        return $this->leftSkill;
    }

    /**
     * @param mixed $middleSkill
     */
    public function setMiddleSkill($middleSkill) {
        $this->middleSkill = $middleSkill;
    }

    /**
     * @return mixed
     */
    public function getMiddleSkill() {
        return $this->middleSkill;
    }

    /**
     * @param int $order
     */
    public function setOrder($order) {
        $this->order = $order;
    }

    /**
     * @return int
     */
    public function getOrder() {
        return $this->order;
    }

    /**
     * @param mixed $rightSkill
     */
    public function setRightSkill($rightSkill) {
        $this->rightSkill = $rightSkill;
    }

    /**
     * @return mixed
     */
    public function getRightSkill() {
        return $this->rightSkill;
    }

    /**
     * @param \Bl2\Model\Character $skillTree
     */
    public function setSkillTree($skillTree) {
        $this->skillTree = $skillTree;
    }

    /**
     * @return \Bl2\Model\Character
     */
    public function getSkillTree() {
        return $this->skillTree;
    }

    protected function doValidation() {
        parent::doValidation(); // TODO: Change the autogenerated stub
    }
}