<?php

namespace Bl2\Model;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * Entity object representing a skill.
 * @ORM\Entity
 * @ORM\Table(name="skill", uniqueConstraints={@ORM\UniqueConstraint(name="unique_name", columns={"name"})})
 **/
class Skill extends AbstractEntity {

    /**
     * @ORM\ManyToOne(targetEntity="Character", inversedBy="skills", fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="characterId", referencedColumnName="id")
     * @Serializer\Exclude
     * @var Character
     **/
    protected $character;

    /**
     * @ORM\Column(type="string")
     * @var string
     **/
    protected $name;

    /**
     * @ORM\Column(type="string")
     * @var string
     **/
    protected $text;

    /**
     * @ORM\Column(type="string")
     * @var string
     **/
    protected $image;

    /**
     * @ORM\Column(type="integer")
     * @var int
     **/
    protected $levels;

    /**
     * Creates a new character class by initializing is properties by using the values given in the associative array.
     *
     * @param array $data associative array holding the properties for the character class.
     */
    public function __construct(array $data) {
        parent::__construct($data);
    }

    /**
     * @param \Bl2\Model\Character $character
     */
    public function setCharacter($character) {
        $this->character = $character;
    }

    /**
     * @return \Bl2\Model\Character
     */
    public function getCharacter() {
        return $this->character;
    }

    /**
     * @param string $image
     */
    public function setImage($image) {
        $this->image = $image;
    }

    /**
     * @return string
     */
    public function getImage() {
        return $this->image;
    }

    /**
     * @param int $levels
     */
    public function setLevels($levels) {
        $this->levels = $levels;
    }

    /**
     * @return int
     */
    public function getLevels() {
        return $this->levels;
    }

    /**
     * @param string $name
     */
    public function setName($name) {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * @param string $text
     */
    public function setText($text) {
        $this->text = $text;
    }

    /**
     * @return string
     */
    public function getText() {
        return $this->text;
    }

    protected function doValidation() {
        parent::doValidation(); // TODO: Change the autogenerated stub
    }
}